# AI Factory - State Schema v1.4
# Deployment field added for test environment management

meta:
  project_id: product-example
  repo_url: https://github.com/user/product-example
  created_at: 2026-01-11T00:00:00Z

phase: development  # idea | prp | development | test | human_validation | release

version:
  prp: 1.0
  code: 0.1.0
  docs: 1.0

blocking:
  is_blocked: false
  reason: null  # "test_failure" | "awaiting_human" | "agent_error"
  since: null

actors:
  current: dev_agent
  awaiting_human: false

last_event:
  agent: prp_agent
  action: "PRP v1.0 generated"
  timestamp: 2026-01-11T00:00:00Z
  result: success  # success | failure | partial
  model: "google/gemma-3-27b-it:free"

next_action:
  agent: dev_agent
  action: "implement initial version"
  requires_human_approval: true

artifacts:
  prp: prp/prp.md
  tests: tests/test_specs.md
  docs: docs/architecture.md

health:
  test_pass_rate: null  # 0.0-1.0
  revision_count: 0
  last_human_feedback: null

automation:
  allowed: false
  auto_agents: []  # ["test_agent", "doc_agent"]

agent_models:
  prp_agent: "gemma-free"
  dev_agent: "gemma-free"
  test_agent: "gemma-free"
  doc_agent: "gemma-free"
  rejection_analyzer: "gemma-free"

# v1.4: Deployment management for test environment
deployment:
  status: null              # null | pending | deployed | failed | stopped
  type: web_app            # web_app | cli_tool | api | static
  port: null               # 5001-5010 (assigned port)
  url: null                # /preview/product-name
  pid: null                # Process ID for stopping
  started_at: null         # ISO timestamp
  last_activity: null      # ISO timestamp (for idle timeout)
